// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg9LhLvbUKcWxO6rNabImM3vIQLwh0R6A',
    appId: '1:37925678934:web:104fc7b18fba132aeeb0f7',
    messagingSenderId: '37925678934',
    projectId: 'mad-project2-5a7b8',
    authDomain: 'mad-project2-5a7b8.firebaseapp.com',
    storageBucket: 'mad-project2-5a7b8.firebasestorage.app',
    measurementId: 'G-8LSRJGVXGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0UN-DUc7jWSCOC9akgJilrx_km85WWHE',
    appId: '1:37925678934:android:a57ade46c321ddddeeb0f7',
    messagingSenderId: '37925678934',
    projectId: 'mad-project2-5a7b8',
    storageBucket: 'mad-project2-5a7b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtNaYEW2n2c6EkI5v-lD7FoCw8IyxOcYw',
    appId: '1:37925678934:ios:753c656e5750b2a9eeb0f7',
    messagingSenderId: '37925678934',
    projectId: 'mad-project2-5a7b8',
    storageBucket: 'mad-project2-5a7b8.firebasestorage.app',
    iosBundleId: 'com.example.foodRunner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtNaYEW2n2c6EkI5v-lD7FoCw8IyxOcYw',
    appId: '1:37925678934:ios:753c656e5750b2a9eeb0f7',
    messagingSenderId: '37925678934',
    projectId: 'mad-project2-5a7b8',
    storageBucket: 'mad-project2-5a7b8.firebasestorage.app',
    iosBundleId: 'com.example.foodRunner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg9LhLvbUKcWxO6rNabImM3vIQLwh0R6A',
    appId: '1:37925678934:web:bfc5fa8ddbcd2b8deeb0f7',
    messagingSenderId: '37925678934',
    projectId: 'mad-project2-5a7b8',
    authDomain: 'mad-project2-5a7b8.firebaseapp.com',
    storageBucket: 'mad-project2-5a7b8.firebasestorage.app',
    measurementId: 'G-KZ3KMQZX0Z',
  );

}